language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
    - "node_modules"
install:
  - yarn install
script:
  - yarn build
  - yarn lint
  - yarn build-storybook
